server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
     
keycloak:
  realm: OfficerPro
  auth-server-url: http://localhost:8080
  resource: OfficerPro
  credentials:
    secret: YOUR_CLIENT_SECRET   # replace with actual Keycloak client secret
  bearer-only: false

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: OfficerPro
            client-secret: YOUR_CLIENT_SECRET
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/OfficerPro
